### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by geedsen** [sjkp/azure-localhost-tunnel#3]
Although I have the impression there is nobody supporting this any longer, I will still write down some of my findings. First of all using the button on the description page works fine for the deploy but somehow does not generate the required node command for me. It will however if you deploy from powershell. So make sure you do the npm install as described in the readme. But then from powershell do the following: 
1) Connect-AzureRmAccount and 2) New-AzureRmResourceGroupDeployment -Name <yourname>           -ResourceGroupName <yourresourcegroupname>   -TemplateFile c:\temp\azuredeploy.json -storageAccountType Standard_GRS
It will still prompt you for the json file. The json file you can download from here https://raw.githubusercontent.com/sjkp/azure-localhost-tunnel/master/azuredeploy.json

Now this will create the tunnel in azure AND tell you the local command to run. And running the local command will tell you (it takes a long time before you actually see this) that it is running , the last part of the output looks like this:

  key: 'zV89LeftaC9vh5Lkzy0uEw==',
  webSocketVersion: 13,
  protocolFullCaseMap: {},
  requestedProtocols: [],
  requestedExtensions: [],
  cookies: [] }
tunnel
52.166.206.133 connected - Protocol Version 13
connection on localhost: 8907

Now browsing to localhost works just fine, but browsing to to the AppService URL
results in an HTTP 500 error and in the command windows node crashed with the following error

internal/buffer.js:35
    throw new ERR_OUT_OF_RANGE('value', `>= ${min} and <= ${max}`, value);
    ^

RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -1516902427
    at checkInt (internal/buffer.js:35:11)
    at writeU_Int32BE (internal/buffer.js:625:3)
    at Buffer.writeUInt32BE (internal/buffer.js:638:10)
    at WebSocketFrame.toBuffer (D:\Development\downloads\azure-localhost-tunnel-master\node_modules\websocket\lib\WebSocketFrame.js:257:24)
    at WebSocketConnection.sendFrame (D:\Development\downloads\azure-localhost-tunnel-master\node_modules\websocket\lib\WebSocketConnection.js:857:43)
    at WebSocketConnection.fragmentAndSend (D:\Development\downloads\azure-localhost-tunnel-master\node_modules\websocket\lib\WebSocketConnection.js:793:14)
    at WebSocketConnection.sendUTF (D:\Development\downloads\azure-localhost-tunnel-master\node_modules\websocket\lib\WebSocketConnection.js:733:10)
    at WebSocketConnection.send (D:\Development\downloads\azure-localhost-tunnel-master\node_modules\websocket\lib\WebSocketConnection.js:720:14)
    at Socket.<anonymous> (D:\Development\downloads\azure-localhost-tunnel-master\client.js:101:15)
    at Object.onceWrapper (events.js:275:13)

Browsing to the ip address that is shown by node shows the following:

<Code>400</Code>
<Detail>Incorrect request Uri format. TrackingId:1fd41933-1863-4c55-8120-96b3a9107eef_G24, SystemTracker:52.166.202.41:, Timestamp:5/8/2018 10:31:56 AM</Detail>

**Comment by jwisener** [comment]
I also got an error trying to set this up.
